### ISSUE TITLE
中间的停顿功能似乎是失效的，语音直接念出来[p1000]

### ISSUE THREAD

**Issue by wxtt522** [vegetable09/iflytek_tts_python_webapi_sophisticated_demo#3]
'怎么办\n[p1000]', '这个时候\n[p1000]', '你肯定会  一脸雾水莫名躺Q\n[p1000]', 

如上是我生成的text，最后语音在每一句结尾都念出来p1000，是科大讯飞不支持这种方式了吗？还是我生成的文本有问题

**Comment by wxtt522** [comment]
破案了，不要用xiaoyan播报员，其它是ok的

**Comment by voyager0003** [comment]
欢迎交流~
